//Singup 

Post http://localhost:8800/api/auth/signup
Content-Type:application/json

{
 "name":"Test New 4",
  "email": "TestNew4kmd@.edu.mm",
  "password": "123456",
  "DateOFBirth":"dad",
  "NRC":"adfda",
  "PhNo":"0232389923",
  "Address":"afldkajl"
}

####
Post http://localhost:8800/api/auth/Adminsignin 
Content-Type:application/json

{
  "email":"Lumin@543664",
  "password": "Aunglin@543664"
}


####
Post http://localhost:8800/api/auth/Judgesignup
Content-Type:application/json

{
  "name":"Aung Ko Latt",
  "email": "AungKoLatt.edu.mm",
  "password": "123456",
   "PhNo":"0232389923",
  "History":"0232389923"
}

###
Post http://localhost:8800/api/auth/Adminsignup
Content-Type:application/json

{
  "name":"Test New 1",
  "email": "TestNew1kmd.edu.mm",
  "password": "123456",
  "DateOFBirth":"dad",
  "NRC":"adfda",
  "PhNo":"0232389923",
  "Address":"afldkajl",
  "Role":"Contestant"
}

####
Get http://localhost:8800/api/users/total

####
Get http://localhost:8800/api/judges/total

####
Post http://localhost:8800/api/auth/signin
Content-Type:application/json

{
  "email":"HlwanPaing2012@gmail.com",
  "password": "Aunglin@543664",
  "Role":"Judge"
}

####

PUT http://localhost:8800/api/users/65ce3752fa5e
Content-Type:application/json

{
  "name":"Updated TestingADF"
}


####

DELETE  http://localhost:8800/api/users/660db07f397d8edc995f9a5b

####
DELETE  http://localhost:8800/api/videos/6612ece715a7b268c76e605a


####
Get  http://localhost:8800/api/users/find/660dafa9208578dc715ace52

###
get http://localhost:8800/api/videos/find/661ab5439801b4f5031e3a79
####

Put http://localhost:8800/api/users/sub/660cd66e7fe559b6a5fe5315

####
Put http://localhost:8800/api/users/unsub/660cd66e7fe559b6a5fe5315

####
Put http://localhost:8800/api/users/like/661ab5439801b4f5031e3a79


####
Put http://localhost:8800/api/users/Extralike/660d7f3949b6d75b51875a42

####

Put http://localhost:8800/api/users/Unlike/660d7efa49b6d75b51875a07

#####
Post http://localhost:8800/api/videos
Content-Type:application/json

{
    "title": "Test New Video 22",
    "desc": "Test Video Video 22",
    "imgUrl": "Test Video 22",
    "videoUrl": "Test Video 22 "

}

#####
Put http://localhost:8800/api/videos/65cf6939383155d9b876c5d4
Content-Type:application/json

{
    "title": "Test Video 12",
    "desc": "Test Video 12"
   

}
####
Post http://localhost:8800/api/news
Content-Type:application/json


{
    "title": "Test Video 6",
    "desc": "Test Video ",
    "imgUrl": "Test Video 5 "
   

}

#####
get http://localhost:8800/api/users/find/660dafa9208578dc715ace52


####


#####
get http://localhost:8800/api/videos/sub


#####

Put http://localhost:8800/api/like/65cf6b739198c3f1b24a6994



#####

POST  http://localhost:8800/api/auth/google


####
POST http://localhost:8800/api/comments/
Content-Type:application/json

{
  "videoId":"65f59161031448a1fe85528c",
  "desc":"Test1"

}


####
POST http://localhost:8800/api/videos/saveVideoDetail
Content-Type:application/json

{
  "videoId":"65f59161031448a1fe85528c",
  "Transaction":"Update"

}

####
Get http://localhost:8800/api/comments/65f59161031448a1fe85528c


####
GET  http://localhost:8800/api/videos/VoteMe


####
PUT http://localhost:8800/api/videos/view/660967d51458925b4155bad6

####

Get http://localhost:8800/api/videos/getVideo/65ce3752faea6c00e403d15e


####
Get  http://localhost:8800/api/news/lastest


####
Get http://localhost:8800/api/auth/findAdmin/6604160627c1eab574eaadc0



####
Post  http://localhost:8800/api/VoteDetail
Content-Type:application/json

{
    "videoId":"65f59161031448a1fe85528c",
  "VoteType":"Normal Vote",
  "Transition": "Vote"
}

#####
Post http://localhost:8800/api/users/Payment
Content-Type:application/json

{
    "TotalQuantity":9,
  "TotalPrice":20
}


####
Get  http://localhost:8800/api/users/find/660dafa9208578dc715ace52


######
Get http://localhost:8800/api/videos/findMostLikedVideo


####
Get http://localhost:8800/api/judges/find/6622ec698c902c3575bbad70